CREATE TABLE IF NOT EXISTS java_lessons.users
(

    id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    age  INT
);


CREATE TABLE IF NOT EXISTS java_lessons.account
(
    id    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    money INT
);